
create type recipe_category as enum( 
  'Dessert',
  'Vegetarian',
  'Quick',
  'Vegan',
  'Drink'
);

create table "recipes" (
    "id" integer generated by default as identity primary key,
    "title" text not null,
    "description" text,
    "image_url" text not null,
    "ingredients" text[],
    "instructions" text[],
    "categories" recipe_category,
    "created_at" timestamp with time zone default now()
);

