-- recipes.sql
CREATE TABLE if not exists recipes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL, -- for RLS
    title text NOT NULL,
    description text,
    image_url text NOT NULL,
    ingredients text[],
    instructions text[],
    category_id bigint REFERENCES categories(id),
    is_public boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);